name = "sakariresult"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./dist" }

[[d1_databases]]
binding = "DB"
database_name = "sarkari-portal-db"
database_id = "48e94f25-b04b-4e1f-86cc-0cb4d87423d9"
migrations_dir = "./migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "sarkari-portal-storage"

[triggers]
crons = ["*/15 * * * *"]
